### ISSUE TITLE
Typo i found

### ISSUE THREAD

**Issue by srcdes** [msfrisbie/professional-javascript-for-web-developers#1]
In the `Introduction` section...

Chrome has Blink/V8, Firefox has Gecko/**SpiderMoney**, and Safari has WebKit/JavaScriptCore.

to

Chrome has Blink/V8, Firefox has Gecko/**SpiderMonkey**, and Safari has WebKit/JavaScriptCore.

**Comment by msfrisbie** [comment]
Added to errata page
