### ISSUE TITLE
Typo in Chapter 3, page 26, Case-Sensitivity

### ISSUE THREAD

**Issue by goldsipe** [msfrisbie/professional-javascript-for-web-developers#15]
The section on Case-Sensitivity ends with "however, typeof is a perfectly valid function name." That is incorrect as written (and conflicts with the beginning of the sentence). I assume "typeof" was intended to have one or more capitalized letters, so that it no longer matches a keyword.

**Comment by msfrisbie** [comment]
Resolved in new edition
