### ISSUE TITLE
Chapter Functions, p.356

### ISSUE THREAD

**Issue by mihailstefanov** [msfrisbie/professional-javascript-for-web-developers#4]
Why you do so complicated check like
```javascript
name = (typeof name !== 'undefined') ? name : 'Henry';
```
inserted of
```javascript
name = name || 'Henry';
```
or if you want to handle "" case?
```
name = (name !== undefined) ? name : 'Henry';
```

**Comment by msfrisbie** [comment]
Admittedly, this example is a bit verbose. There are a number of more concise ways to check for a missing parameter. The intent if this particular example is to contrast to what is offered by default parameter values.
